apiVersion: v1
kind: Service
metadata:
  name: imdb
  namespace: imdb
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30080
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: imdb
