apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeat
  namespace: heartbeat
  labels:
    app.kubernetes.io/name: heartbeat
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  selector:
    matchLabels:
      app: heartbeat
  template:
    metadata:
      labels:
        app: heartbeat
    spec:
      containers:
        - name: app
          image: ghcr.io/kubernetes101/heartbeat:latest
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 200m
              memory: 64Mi
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          readinessProbe:
            initialDelaySeconds: 5
            failureThreshold: 60
            periodSeconds: 2
            httpGet:
              path: /readyz
              port: 8080
          livenessProbe:
            initialDelaySeconds: 60
            periodSeconds: 60
            httpGet:
              path: /healthz
              port: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: heartbeat
  namespace: heartbeat
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: http
      nodePort: 31080
      protocol: TCP
      name: http
  selector:
    app: heartbeat
