apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: monitoring
data:
  grafana.ini:  |
    [security]
    admin_user = $__file{/etc/config/secrets/username}
    admin_password = $__file{/etc/config/secrets/password}
    [dashboards]
    default_home_dashboard_path = "/var/lib/grafana/dashboards/imdb/imdb.json"

---

apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
  namespace: monitoring
type: Opaque
data:
  username: YWRtaW4=
  password: a3ViZWNvbjEwMQ==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 472
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups:
          - 0    
      containers:
      - name: grafana
        image: ghcr.io/kubernetes101/grafana:8.1.1
        ports:
        - name: grafana
          containerPort: 3000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          runAsNonRoot: true
          runAsUser: 10001            
        volumeMounts:
          - name: grafana-secrets
            mountPath: /etc/config/secrets
          - name: grafana-storage
            mountPath: /var/lib/grafana
          - name: grafana-datasources
            mountPath: /etc/grafana/provisioning/datasources
            readOnly: false
          - name: grafana-config
            mountPath: /etc/grafana/grafana.ini
            subPath: grafana.ini
          - name: grafana-dashboard-provider
            mountPath: /etc/grafana/provisioning/dashboards/dashboardProvider.yaml
            subPath: dashboardProvider.yaml
          - name: dashboards-imdb
            mountPath: /var/lib/grafana/dashboards/imdb
          - name: dashboards-dotnet
            mountPath: /var/lib/grafana/dashboards/dotnet
      volumes:
        - name: grafana-secrets
          secret:
            secretName: grafana-secrets
        - name: grafana-storage
          hostPath:
            path: /grafana
        - name: grafana-datasources
          configMap:
              defaultMode: 420
              name: grafana-datasources
        - name: grafana-config
          configMap:
            name: grafana-config
        - name: grafana-dashboard-provider
          configMap:
            name: grafana-dashboard-provider
        - name: dashboards-imdb
          configMap:
            name: grafana-dashboards-imdb
        - name: dashboards-dotnet
          configMap:
            name: grafana-dashboards-dotnet

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
